### ISSUE TITLE
Installation_uuid not splitting data as expected

### ISSUE THREAD

**Issue by nditada** [instedd/telemetry_rails#102]
See attached. There's only 1 installation for Pollit, and all values are the same for each installation that Kibana is charting. Maybe it's a misunderstanding of how Kibana is translating the settings to the actual ES query?

<img width="1434" alt="screen shot 2016-02-23 at 8 29 35 pm" src="https://cloud.githubusercontent.com/assets/1359189/13270355/4d4f8d98-da6c-11e5-97a5-6a15f75bf5b4.png">

**Comment by juanedi** [comment]
The problem here is that `installation_uuid` is stored as an analyzed field in elasticsearch. This means that a uuid such as `a3abc6af-5a21-4eed-8ec3-e6b3487a7e93` will produce 5 buckets (one for each part of the string).

What we see in that screenshot is data from a single installation displayed 5 times. This makes sense since there is currently only one pollit installation reporting to telemetry.
